---
- name: Provision Developer Workstation
  hosts: [all]
  gather_facts: true
  tasks: []
  roles:
    - zsh
    - common
    - role: roles/wsl
      when: ansible_facts.env["WSL_DISTRO_NAME"] is defined
    - ssh
    - git
    - kubernetes
    - vim
    - helm
