---
- name: check if rules file exists
  stat:
    path: "{{ ansible_facts.user_dir }}/.ssh/id_rsa"
  register: ssh
- name: Generate an OpenSSH keypair with the default values (4096 bits, rsa)
  community.crypto.openssh_keypair:
    path: "{{ ansible_facts.user_dir }}/.ssh/id_rsa"
  when: not ssh.stat.exists
