---
- name: Install ZSH
  become: true
  ansible.builtin.apt:
    name: "{{item}}"
    state: present
    update_cache: yes
  with_items:
    - zsh
    - fzf
    - rsync
- name: Install Pygments python package
  ansible.builtin.pip:
    name: Pygments
- block:
    - stat:
        path: "{{ ansible_facts.user_dir }}/.oh-my-zsh"
      register: oh_my_zsh_directory
    - ansible.posix.synchronize:
        src: "{{ ansible_facts.user_dir }}/.oh-my-zsh"
        dest: "{{ ansible_facts.user_dir }}/.oh-my-zsh.{{ lookup('community.general.random_string') }}"
      when: oh_my_zsh_directory.stat.exists
    - file:
        path: "{{ ansible_facts.user_dir }}/.oh-my-zsh"
        state: absent
    - name: install ohmyzsh
      ansible.builtin.shell:
        cmd: sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
- name: Git checkout
  ansible.builtin.git:
    depth: 1
    repo: https://github.com/romkatv/powerlevel10k.git
    dest: "{{ ansible_facts.user_dir }}/.oh-my-zsh/themes/powerlevel10k"
- name: Configure zshrc
  ansible.builtin.copy:
    src: .zshrc
    dest: "{{ ansible_facts.user_dir }}/.zshrc"
    mode: "u=rw,g=r,o="
    backup: yes
- name: Configure Powerlevel10k
  ansible.builtin.copy:
    src: .p10k.zsh
    dest: "{{ ansible_facts.user_dir }}/.p10k.zsh"
    mode: "u=rw,g=r,o="
    backup: yes
- name: change user shell to zsh
  become: true
  user:
    name: "{{ ansible_user_id }}"
    shell: /bin/zsh
