---
- name: Add Git APT
  become: true
  ansible.builtin.apt_repository:
    repo: ppa:git-core/ppa
- name: Install Git
  become: true
  ansible.builtin.apt: 
    name: git
    state: present
    update_cache: yes
- name: Configure Git
  community.general.git_config:
    name: "{{ item.name }}"
    scope: global
    value: "{{ item.value }}"
  with_items:
    - name: core.fsmonitor
      value: ""
    - name: rebase.updateRefs
      value: 'true'
    - name: core.editor
      value: vim
    - name: user.name
      value: "{{ git.username }}"
    - name: user.email
      value: "{{ git.email }}"
    - name: core.pager
      value: ""
    - name: help.autocorrect
      value: 5
    - name: color.ui
      value: 'true'
    - name: core.autocrlf
      value: 'true'
    - name: diff.renameLimit
      value: 65553
    - name: diff.renames
      value: 'true'
    - name: pager.log
      value: 'false'
    - name: merge.conflictstyle
      value: diff3
    - name: diff.algorithm
      value: histogram
    - name: feature.manyFiles
      value: 'true'
    - name: init.defaultBranch
      value: main
    - name: rebase.autosquash
      value: 'true'
    - name: alias.lol
      value: 'll -1 --stat'
    - name: alias.last
      value: 'log -1 --stat'
    - name: alias.ll
      value: 'log --pretty=format:"%C(yellow)%h%Creset %s %Cblue[%cn|%ad|%D]%Creset" --date="format:%Y-%m-%d" --decorate'
    - name: alias.unstage
      value: 'reset HEAD --'
    - name: alias.st
      value: 'status --short --branch'
    - name: alias.sdiff
      value: 'difftool --tool="vimdiff" -y'
    - name: alias.search
      value: '!git rev-list --all | xargs git grep --fixed-strings'
    - name: alias.renormalize
      value: '!git add --renormalize . && git commit -m "Introduce end-of-line normalization"'
    - name: alias.purge
      value: '!git rm -r --force . && git clean -xd --force'
    - name: alias.b
      value: '!git for-each-ref --sort="-authordate" --format="%(authordate)%09%(objectname:short)%09%(refname)" refs/heads | sed -e "s-refs/heads/--"'
    - name: alias.ac
      value: '!git add -all && git commit --all --message'
    - name: alias.rebase-date
      value: '!_f() { git rebase "${1}" --rebase-merges --committer-date-is-author-date; }; _f'
    - name: alias.read-config
      value: 'config --global --list'
    - name: alias.rebase-fixup
      value: 'rebase --interactive --autosquash --rebase-merges'
    - name: alias.json-log
      value: '!_f() { git raw-json-log ${@} | sed ''s/\"/\\\"/g''| sed ''s/__SEPARATOR__/\"/g'' | jq --slurp --monochrome-output .; }; _f'
    - name: alias.ammend-this
      value: '!git add --all && git commit --amend --no-edit'
    - name: alias.raw-json-log
      value: "log --pretty=format:'{__SEPARATOR__commit__SEPARATOR__: __SEPARATOR__%H__SEPARATOR__,__SEPARATOR__abbreviated_commit__SEPARATOR__: __SEPARATOR__%h__SEPARATOR__,__SEPARATOR__tree__SEPARATOR__: __SEPARATOR__%T__SEPARATOR__,__SEPARATOR__abbreviated_tree__SEPARATOR__: __SEPARATOR__%t__SEPARATOR__,__SEPARATOR__parent__SEPARATOR__: __SEPARATOR__%P__SEPARATOR__,__SEPARATOR__abbreviated_parent__SEPARATOR__: __SEPARATOR__%p__SEPARATOR__,__SEPARATOR__refs__SEPARATOR__: __SEPARATOR__%D__SEPARATOR__,__SEPARATOR__encoding__SEPARATOR__: __SEPARATOR__%e__SEPARATOR__,__SEPARATOR__subject__SEPARATOR__: __SEPARATOR__%s__SEPARATOR__,__SEPARATOR__sanitized_subject_line__SEPARATOR__: __SEPARATOR__%f__SEPARATOR__,__SEPARATOR__body__SEPARATOR__: __SEPARATOR__%b__SEPARATOR__,__SEPARATOR__commit_notes__SEPARATOR__: __SEPARATOR__%N__SEPARATOR__,__SEPARATOR__verification_flag__SEPARATOR__: __SEPARATOR__%G?__SEPARATOR__,__SEPARATOR__signer__SEPARATOR__: __SEPARATOR__%GS__SEPARATOR__,__SEPARATOR__signer_key__SEPARATOR__: __SEPARATOR__%GK__SEPARATOR__,__SEPARATOR__author__SEPARATOR__: {__SEPARATOR__name__SEPARATOR__: __SEPARATOR__%aN__SEPARATOR__, __SEPARATOR__email__SEPARATOR__: __SEPARATOR__%aE__SEPARATOR__, __SEPARATOR__date__SEPARATOR__: __SEPARATOR__%aD__SEPARATOR__},__SEPARATOR__commiter__SEPARATOR__: { __SEPARATOR__name__SEPARATOR__: __SEPARATOR__%cN__SEPARATOR__, __SEPARATOR__email__SEPARATOR__: __SEPARATOR__%cE__SEPARATOR__, __SEPARATOR__date__SEPARATOR__: __SEPARATOR__%cD__SEPARATOR__}}'"
...