---
- name: Create .hushlogin to remove prompt of WSL
  ansible.builtin.file:
    path: "{{ ansible_facts.user_dir }}/.hushlogin"
    state: touch
    mode: "u=rw,g=r,o="
- name: Enable automount; Enable wsl/linux fmask interop
  become: true
  ansible.builtin.blockinfile:
    create: true
    marker: "# {mark} ANSIBLE MANAGED BLOCK: AUTOMOUNT"
    path: "/etc/wsl.conf"
    mode: "u=rw,g=rw,o="
    block: |
      [automount]
      enabled = true
      options = "metadata,umask=22,fmask=11"
