---
# TODO: Add mvn
# TODO: Add docker
# TODO: Add universal plumber
# TODO: Add minikube
# TODO: Add tilt
# TODO: Add vscode
# TODO: Add ssh server
# TODO: Add intellij idea
# TODO: Add java version manager
# TODO: Add yq
# TODO: Add screenfetch
# TODO: Add autojump
# TODO: Add lazygit
# TODO: Add fd
# TODO: Add ripgrep
# TODO: Add lazydocker
# TODO: Add ctop
# TODO: Add tldr
# TODO: Add howdoi
# TODO: Add icdiff
- name: Setup brew
  import_tasks: setup-brew.yml
- name: Setup Kubernetes
  import_tasks: setup-kubernetes.yml
- become: true
  ansible.builtin.apt:
    name: "{{item}}"
    state: present
    update_cache: yes
  with_items:
    - dos2unix
    - mc
    - jq
- ansible.builtin.shell: "{{item.cmd}}"
  args:
    creates: "{{ item.creates }}"
  with_items:
    - cmd: VERSION=v0.39.3 curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/${VERSION}/install.sh | bash && nvm install --lts
      creates: "{{ ansible_facts.user_dir }}/.nvm/nvm.sh"
- ansible.builtin.script: |
    brew install gcc
- community.general.homebrew:
    name: k9s
    state: present
