---
# TODO: Add mvn
# TODO: Add docker
# TODO: Add universal plumber
# TODO: Add minikube
# TODO: Add tilt
# TODO: Add vscode
# TODO: Add ssh server
# TODO: Add intellij idea
# TODO: Add java version manager
# TODO: Add yq
# TODO: Add ctop
# TODO: Add tldr
# TODO: Add howdoi
# TODO: Add icdiff
- name: Setup brew
  import_tasks: setup-brew.yml
- name: Setup Kubernetes
  import_tasks: setup-kubernetes.yml
- become: true
  ansible.builtin.apt:
    name: "{{item}}"
    state: present
    update_cache: yes
  with_items:
    - dos2unix
    - mc
    - jq
    - screenfetch
    - ripgrep
    - fd-find
    - autojump
    - curl
- ansible.builtin.shell: "{{item.cmd}}"
  args:
    creates: "{{ item.creates }}"
  with_items:
    - cmd: VERSION=v0.39.3 curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/${VERSION}/install.sh | bash && nvm install --lts
      creates: "{{ ansible_facts.user_dir }}/.nvm/nvm.sh"
    - cmd: |
        VERSION=v3.11.2 wget --output-document {{ ansible_facts.user_dir }}/.local/bin/helm.tgz https://get.helm.sh/helm-${VERSION}-linux-amd64.tar.gz && \
        tar -xf {{ ansible_facts.user_dir }}/.local/bin/helm.tgz -C {{ ansible_facts.user_dir }}/.local/bin linux-amd64/helm && \
        mv {{ ansible_facts.user_dir }}/.local/bin/linux-amd64/helm {{ ansible_facts.user_dir }}/.local/bin/helm && \
        rm -r {{ ansible_facts.user_dir }}/.local/bin/linux-amd64 && \
        chmod +x {{ ansible_facts.user_dir }}/.local/bin/helm
      creates: "{{ ansible_facts.user_dir }}/.local/bin/helm"
- community.general.homebrew:
    name: "{{item}}"
    state: present
  with_items:
    - k9s
    - gcc
    - jesseduffield/lazygit/lazygit
    - jesseduffield/lazydocker/lazydocker